package Ejercicio_3_TRES;
import javax.swing.JOptionPane;

/**
 *
 * @author AA2020
 */
public class Ventana_Ejercicio_TRES extends javax.swing.JFrame {
    Industria industriaObj;
    Fundacion fundacionObj;
    Almacen almacenObj;

    /**
     * Creates new form Ventana_Ejercicio_TRES
     */
    public Ventana_Ejercicio_TRES() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTEXTO = new javax.swing.JLabel();
        btnIndustria = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnFundacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instituciones Salvadoreñas");

        lblTEXTO.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblTEXTO.setForeground(new java.awt.Color(0, 0, 255));
        lblTEXTO.setText("instituciones salvadoreñas");

        btnIndustria.setBackground(new java.awt.Color(102, 255, 102));
        btnIndustria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_3_TRES/Imagenes/radioactivo.png"))); // NOI18N
        btnIndustria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndustriaActionPerformed(evt);
            }
        });

        btnAlmacen.setBackground(new java.awt.Color(255, 255, 102));
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_3_TRES/Imagenes/edificios.png"))); // NOI18N
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        btnFundacion.setBackground(new java.awt.Color(255, 102, 102));
        btnFundacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_3_TRES/Imagenes/bandera.png"))); // NOI18N
        btnFundacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIndustria)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlmacen)
                        .addGap(18, 18, 18)
                        .addComponent(btnFundacion)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTEXTO)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTEXTO)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIndustria)
                    .addComponent(btnAlmacen)
                    .addComponent(btnFundacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndustriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndustriaActionPerformed
        industriaObj = new Industria(150, "Chernobyl", "Privada", "70");
        JOptionPane.showMessageDialog(this, "Industria: " + industriaObj._nombre + "\nTipo de Industria: "+ industriaObj._tipo + "\nAños en Función: "+ industriaObj._anio + "\nCantidad de Maquinarias: "+ industriaObj._cantidadMaquinaria + "\n" + industriaObj.Funcionando());
    }//GEN-LAST:event_btnIndustriaActionPerformed

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        almacenObj = new Almacen(145, "El Escorial", "Pública", "34");
        JOptionPane.showMessageDialog(this, "Nombre del Almacén: " + almacenObj._nombre + "\nTipo de Almacén: "+ almacenObj._tipo + "\nAños en Función: "+ almacenObj._anio + "\nCantidad de Artículos: "+ almacenObj._cantidadArticulos + "\n"+ almacenObj.Saludar());
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnFundacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundacionActionPerformed
        fundacionObj = new Fundacion("Marlon Rosemberg Pacheco", "Quédate En Casa", "Pública", "2");
        JOptionPane.showMessageDialog(this, "Fundación: " + fundacionObj._nombre + "\nTipo de Fundación: "+ fundacionObj._tipo + "\nAños de Servicio: "+ fundacionObj._anio + "\nFundador: "+ fundacionObj._fundadorFundacion + "\n"+ fundacionObj.FraseFundacion());
    }//GEN-LAST:event_btnFundacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced industriaObj Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Ejercicio_TRES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnFundacion;
    private javax.swing.JButton btnIndustria;
    private javax.swing.JLabel lblTEXTO;
    // End of variables declaration//GEN-END:variables
}
