package Ejercicio_1_UNO;
import javax.swing.JOptionPane;

/**
 *
 * @author AA2020
 */
public class Ventana_Ejercicio_UNO extends javax.swing.JFrame {
    Piano pianoObj;
    Guitarra guitarraObj;
    Trompeta trompetaObj;

    /** Creates new form Ventana_Ejercicio_UNO */
    public Ventana_Ejercicio_UNO() {
        //piano = new Piano(tipo, nombre, color, tamanio)
        pianoObj = new Piano("Clásico", "YAMAHA", "Rojo Oscuro", "10 Octavas");
        //guitar = new Guitarra(nombre, color, tamanio)
        guitarraObj = new Guitarra("Gibson J200", "Morado", "155cm");
        //trom = new Trompeta(nombre, color, tamanio)
        trompetaObj = new Trompeta("Piccolo", "Oro", "50cm");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTEXTO = new javax.swing.JLabel();
        btnPiano = new javax.swing.JButton();
        btnGuitarra = new javax.swing.JButton();
        btnTrompeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instrumentos");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lblTEXTO.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblTEXTO.setForeground(new java.awt.Color(0, 0, 255));
        lblTEXTO.setText("LA CASA DE LOS INSTRUMENTOS");

        btnPiano.setBackground(new java.awt.Color(102, 255, 102));
        btnPiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_1_UNO/Imagenes/keyboard.png"))); // NOI18N
        btnPiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPianoActionPerformed(evt);
            }
        });

        btnGuitarra.setBackground(new java.awt.Color(255, 255, 102));
        btnGuitarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_1_UNO/Imagenes/string-instrument.png"))); // NOI18N
        btnGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuitarraActionPerformed(evt);
            }
        });

        btnTrompeta.setBackground(new java.awt.Color(255, 102, 102));
        btnTrompeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio_1_UNO/Imagenes/trumpet.png"))); // NOI18N
        btnTrompeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrompetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTEXTO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPiano)
                .addGap(18, 18, 18)
                .addComponent(btnGuitarra)
                .addGap(18, 18, 18)
                .addComponent(btnTrompeta)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTEXTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPiano)
                    .addComponent(btnGuitarra)
                    .addComponent(btnTrompeta))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPianoActionPerformed
        JOptionPane.showMessageDialog(this, "Soy un piano: "+ pianoObj.GetNombreInstrumento()+ ", mi color es: " + pianoObj.GetColorInstrumento()+", mi tamaño es de: " + pianoObj.GetTamanioInstrumento()+", y genero este sonido: "+ pianoObj.GenerarSonido());
    }//GEN-LAST:event_btnPianoActionPerformed

    private void btnGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuitarraActionPerformed
        JOptionPane.showMessageDialog(this, "Soy una guitarra: "+ guitarraObj.GetNombreInstrumento()+ ", mi color es: " + guitarraObj.GetColorInstrumento()+", mi tamaño es de: " + guitarraObj.GetTamanioInstrumento()+", tengo " + guitarraObj._guitarraCuerdas + " número de cuerdas, y genero este sonido: " + guitarraObj.GenerarSonido());
    }//GEN-LAST:event_btnGuitarraActionPerformed

    private void btnTrompetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrompetaActionPerformed
        JOptionPane.showMessageDialog(this, "Soy una trompeta: "+ trompetaObj.GetNombreInstrumento()+ ", mi color es: " + trompetaObj.GetColorInstrumento()+", mi tamaño es de: " + trompetaObj.GetTamanioInstrumento()+", y genero este sonido: "+ trompetaObj.GenerarSonido());
    }//GEN-LAST:event_btnTrompetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_UNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_UNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_UNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ejercicio_UNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Ejercicio_UNO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuitarra;
    private javax.swing.JButton btnPiano;
    private javax.swing.JButton btnTrompeta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTEXTO;
    // End of variables declaration//GEN-END:variables

}
